[phases.setup]
nixPkgs = ['python3', 'gcc', 'wkhtmltopdf']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  '. /opt/venv/bin/activate',
  'python -m compileall app/'
]

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT' 