[build]
builder = "nixpacks"
# buildCommand = "pip install -r requirements.txt" # Comment out or remove if nixpacks.toml handles installation

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health" # Updated to new health check endpoint
healthcheckTimeout = 100 